var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/payment/cancel/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0926uwj._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jk5ehi._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_07pmen0.js")
R.c("server/chunks/ssr/[root-of-the-server]__11fvo29._.js")
R.c("server/chunks/ssr/node_modules_next_dist_03nkrli._.js")
R.c("server/chunks/ssr/_02b23er._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_payment_cancel_page_actions_0-wv1-3.js")
R.m(10510)
module.exports=R.m(10510).exports
