var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/medical-disclaimer/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g9uyk4._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jk5ehi._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0duor78.js")
R.c("server/chunks/ssr/[root-of-the-server]__11fvo29._.js")
R.c("server/chunks/ssr/node_modules_next_dist_03nkrli._.js")
R.c("server/chunks/ssr/_02b23er._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_medical-disclaimer_page_actions_10~u9s8.js")
R.m(8214)
module.exports=R.m(8214).exports
