var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/products/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__11ehykl._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0jk5ehi._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0qm4t~~.js")
R.c("server/chunks/ssr/[root-of-the-server]__11fvo29._.js")
R.c("server/chunks/ssr/node_modules_next_dist_03nkrli._.js")
R.c("server/chunks/ssr/_02b23er._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_products_page_actions_121wx.i.js")
R.m(57006)
module.exports=R.m(57006).exports
